# -*- coding: utf-8 -*-
"""developer arenaW1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d76zIioLod_y6TRdzuW-cWAcV95b_aUb
"""

# Personal Introduction Program
# A simple program to collect and display user information

print("=" * 50)
print("WELCOME TO PERSONAL INTRODUCTION PROGRAM")
print("=" * 50)
print()

# Taking input from user
name = input("Please enter your name: ")
age = input("Please enter your age: ")
hobby = input("Please enter your hobby: ")

print()
print("=" * 50)
print("PERSONAL INTRODUCTION")
print("=" * 50)
print()

# Displaying the welcome message with user information
print(f"Hello! My name is {name}.")
print(f"I am {age} years old.")
print(f"My hobby is {hobby}.")
print()
print("I am very glad that it is my first internship")
print("and I am liking to do it!")
print()
print("=" * 50)